### ISSUE TITLE
sparse_mx_to_sparse_tensor() didnt find

### ISSUE THREAD

**Issue by LiZongyue** [SY1706203/Robustness#2]
In the file of utils.py, the func __sparse_mx_to_sparse_tensor__ is invoked many times and I didn't find it as a build-in func from pytorch neither saw the def in code.

**Comment by SY1706203** [comment]
> In the file of utils.py, the func **sparse_mx_to_sparse_tensor** is invoked many times and I didn't find it as a build-in func from pytorch neither saw the def in code.

sorry, it should be **sparse_mx_to_torch_sparse_tensor** that is defined in the file of utils.py
